name: VegAlts
version: '${project.version}'
main: com.lichenaut.vegalts.VegAlts
api-version: '1.13'
author: lichenaut
description: Adds vegan paths to acquiring animal products.
commands:
    vegalts:
        description: Main command for VegAlts.
        aliases: [va]